### ISSUE TITLE
HTMLdecode does not work if data is from excel tabel

### ISSUE THREAD

**Issue by TobiSonne** [enricoschumann/textutils#2] opened 2019-03-26 14:46 UTC
Hi, 
code should explain itself:

```
library(data.table)
library(openxlsx)
library(magrittr)

Data <- data.table(
  a = c("ä", "ö", "ü"),
  b = c("Ä", "Ö", "Ü")
)

Data[, a] %>% HTMLdecode # everything is fine

Data %>% openxlsx::write.xlsx("Data/Data.xlsx")

Data <- openxlsx::read.xlsx("Data/Data.xlsx") %>% 
  setDT

Data[, a] %>% HTMLdecode # does not work any longer, prints the original values!
```

Is this probably an encoding problem?
It would be really nice if you could solve the problem because I will need your package in the future a few times for writing german E-Mails in R.
Thanks in advance!

**Comment by enricoschumann** [comment] 2019-03-26 14:54
Are you sure you want `HTMLdecode`, not `HTMLencode`?

(If that is the case, you should try the GitHub
version, not the one on CRAN.)

**Comment by enricoschumann** [comment] 2019-03-26 20:45
Here is an example:

```r
install.packages('textutils', 
                 repos = c('http://enricoschumann.net/R', getOption('repos')))

library("data.table")
library("magrittr")
library("textutils")

Data <- data.table(
  a = c("ä", "ö", "ü"),
  b = c("Ä", "Ö", "Ü")
)

Data[, a] %>% HTMLencode
## [1] "&auml;" "&ouml;" "&uuml;"
```

**Comment by TobiSonne** [comment] 2019-03-26 20:50
Thank you, I will check tomorrow if it works for my case and let you know!

**Comment by TobiSonne** [comment] 2019-03-27 06:30
Now it's even worse, I'm sorry

```
Error in gsub(entities[["char"]][i], entities[["ent"]][i], x, fixed = TRUE) : 
  input string 1 is invalid UTF-8
```
In my old case there was a "\xe4" instead of an "ä" for example and it worked.
I don't know if it would work if "ä" was "& a u m l ;" (without spaces of course)
My main problem was/is the following:
https://stackoverflow.com/questions/55352919/nothing-happens-when-i-run-htmldecode-on-a-variable-of-a-dataset

**Comment by TobiSonne** [comment] 2019-03-27 07:00
Oh, I didn't want to close the issue, sorry

**Comment by enricoschumann** [comment] 2019-03-27 07:23
This is caused by the encoding of the input. The function
expects UTF-8-encoded input.

What operating system do you use? What IDE/GUI/Text
editor do you use?

**Comment by TobiSonne** [comment] 2019-03-27 07:29
Windows 10 Education
RStudio Version 1.1.463
I've already set saving to UTF-8

**Comment by enricoschumann** [comment] 2019-03-27 07:35
What do you see when you say
```r
s <- "ä"
Encoding(s)
```
in RStudio? I don't use RStudio, so I cannot directly test.

I just committed a (small) update to the package (it's also on my website, so you can install as above). Here is a slightly changed version of your example:

```r
library("openxlsx")
library("magrittr")
library("textutils")
library("data.table")

Data <- data.table(
  a = c("ä", "ö", "ü"),
  b = c("Ä", "Ö", "Ü")
)

s <- Data[, a]
s %>% HTMLencode
## [1] "&auml;" "&ouml;" "&uuml;"

tempd <- tempdir()
Data %>% openxlsx::write.xlsx(file.path(tempd, "Data.xlsx"))
Data <- openxlsx::read.xlsx(file.path(tempd, "Data.xlsx")) %>% setDT

s <- Data[, a]
s %>% HTMLencode
## [1] "&auml;" "&ouml;" "&uuml;"
```

This works for me now on both Linux and Windows (where I tested with the Windows GUI). Could you try it, please?

**Comment by TobiSonne** [comment] 2019-03-27 07:54
Encoding is "latin1", I am wondering why ...
Your new code leads to the expected result for me.
But what I really need is something like this:
```
HTMLdecode("Herr Müller")
[1] "Herr M\xfcller"
```
This only works with the CRAN version but not if the vector comes i.e. from an excelsheet

**Comment by enricoschumann** [comment] 2019-03-27 08:26
Then, I am afraid, `HTMLencode`/`HTMLdecode` cannot help you. (But why would you want that result at all? HTML entities such as `&uuml;` are ASCII, and so perfectly portable.) 
The behaviour of the CRAN-version was caused because the function assumed that the input was already UTF-8-encoded (as documented). To see the old (unintented) behaviour, say
```r
s <- iconv("Müller", "", "latin1")
Encoding(s) <- "UTF-8"
s
## [1] "M\xfcller"
```
BTW, RStudio uses R, of course, and R per default processes strings in the native locale. So your scripts are converted to UTF-8 when they are written, but once a string is passed to R, it is processed natively (unless explicitly marked as UTF-8).

**Comment by TobiSonne** [comment] 2019-03-27 08:38
Because I want to send multiple (german) E-Mails with R and Outlook like this:
https://stackoverflow.com/questions/26811679/sending-email-in-r-via-outlook
I haven't found another way to display "Müller" like "Müller" than to pass "M\xfcller". If I pass "M&uuml;ller" this leads to "M&uuml;ller" in the E-Mail ...

**Comment by enricoschumann** [comment] 2019-03-27 09:57
Have you tried `M&uuml;ller`? This should work, at least if you can tell Outlook that the message body is HTML.

How about this.
```r
library("mailtools")    ## https://github.com/enricoschumann/mailtools/
sendmail(subject = "Test",
         body = "Hallo, Herr Müller",
         to = "test@testing.org",
         method = "outlook",         
         display.only = TRUE)
```
Works for me, without any additional encoding.

**Comment by TobiSonne** [comment] 2019-03-27 12:11
Oh my god, thank you, this saves my whole day, great!
Why isn't this package on CRAN? The other packages about E-Mails suck so much.
I could not include "Gänsefüßchen" with your function but I couldn't care less.

Edit: OK, because it is not really documented. Please, keep on working on this package. How about text formatation?

**Comment by enricoschumann** [comment] 2019-03-27 19:22
Great. `mailtools` is not on CRAN because I do not use it much on Windows these days, so I cannot really test things. But perhaps I'll reconsider it. In any case, I will update the docs. And by the way, all my packages can be installed from my website (which essentially is a CRAN style repository); see [http://enricoschumann.net/R/packages/mailtools/](http://enricoschumann.net/R/packages/mailtools/)

I think I close this Issue now. Feel free to open a new one for `mailtools`. And regarding your question: text can be formatted by using HTML. I will add examples in the mailtools repository.

**Closed as completed** 2019-03-27 19:28 UTC
